# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/agent/Documents/prefs_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from app.config import get_config, update_config


class Ui_Dialog(object):

    def rejected(self):
        self.window.close()

    def accepted(self):
        for obj, config_map in self.editable_widgets.items():
            if isinstance(obj, QtWidgets.QLineEdit) and not obj.isModified():
                continue
            self.app_config[config_map[0]][config_map[1]] = obj.text() if isinstance(obj, QtWidgets.QLineEdit) else str(obj.isChecked())
        update_config(self.app_config)
        self.window.close()

    def select_directory(self):
        return QtWidgets.QFileDialog.getExistingDirectory()

    def update_source_location(self):
        dir_location = self.select_directory()
        self.app_config["Core"]["ImageDirectory"] = dir_location
        self.sourcesLabel2.setText(dir_location)

    def update_download_location(self):
        dir_location = self.select_directory()
        self.app_config["Core"]["DownloadDirectory"] = dir_location
        self.downloadLocationLabel2.setText(dir_location)

    @staticmethod
    def hide_input(widget):
        widget.setEchoMode(QtWidgets.QLineEdit.Password)

    def setupUi(self, Dialog):
        self.editable_widgets = {}
        self.app_config = get_config()
        self.window = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(565, 373)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")

        # Local config layout
        self.local_tab = QtWidgets.QWidget()
        self.local_tab.setObjectName("local_tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.local_tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.local_tab)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.textBrowser_4)
        self.sourcesLabel = QtWidgets.QLabel(self.local_tab)
        self.sourcesLabel.setObjectName("sourcesLabel")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.sourcesLabel)

        self.sourcesLabel2 = QtWidgets.QLabel(self.local_tab)
        self.sourcesLabel2.setObjectName("sourcesLabel2")
        self.sourcesLabel2.setText(self.app_config.get('Core', 'ImageDirectory'))
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sourcesLabel2)

        self.sourcesLineEdit = QtWidgets.QPushButton("Select", self.local_tab)
        self.sourcesLineEdit.setObjectName("sourcesLineEdit")
        self.sourcesLineEdit.clicked.connect(self.update_source_location)
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sourcesLineEdit)
        self.downloadLocationLabel = QtWidgets.QLabel(self.local_tab)
        self.downloadLocationLabel.setObjectName("downloadLocationLabel")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.downloadLocationLabel)

        self.downloadLocationLabel2 = QtWidgets.QLabel(self.local_tab)
        self.downloadLocationLabel2.setObjectName("downloadLocationLabel2")
        self.downloadLocationLabel2.setText(self.app_config.get('Core', 'DownloadLocation'))
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.downloadLocationLabel2)

        self.downloadLocationLineEdit = QtWidgets.QPushButton("Select", self.local_tab)
        self.downloadLocationLineEdit.setObjectName("downloadLocationLineEdit")
        self.downloadLocationLineEdit.clicked.connect(self.update_download_location)
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.downloadLocationLineEdit)
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.local_tab)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.buttonBox_2)

        self.buttonBox_2.accepted.connect(self.accepted)
        self.buttonBox_2.rejected.connect(self.rejected)

        # Reddit config layout
        self.horizontalLayout_5.addLayout(self.formLayout_7)
        self.tabWidget.addTab(self.local_tab, "")
        self.reddit_tab_2 = QtWidgets.QWidget()
        self.reddit_tab_2.setObjectName("reddit_tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.reddit_tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.clientIDLabel_3 = QtWidgets.QLabel(self.reddit_tab_2)
        self.clientIDLabel_3.setObjectName("clientIDLabel_3")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.clientIDLabel_3)
        self.clientIDLineEdit_3 = QtWidgets.QLineEdit(self.reddit_tab_2)
        self.clientIDLineEdit_3.setText(self.app_config.get('Reddit', 'ClientID'))
        self.clientIDLineEdit_3.setObjectName("clientIDLineEdit_3")
        self.editable_widgets[self.clientIDLineEdit_3] = ("Reddit", "ClientID")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.clientIDLineEdit_3)
        self.clientSecretLabel_3 = QtWidgets.QLabel(self.reddit_tab_2)
        self.clientSecretLabel_3.setObjectName("clientSecretLabel_3")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.clientSecretLabel_3)
        self.clientSecretLineEdit_3 = QtWidgets.QLineEdit(self.reddit_tab_2)
        self.hide_input(self.clientSecretLineEdit_3)
        self.clientSecretLineEdit_3.setObjectName("clientSecretLineEdit_3")
        self.clientSecretLineEdit_3.setText(self.app_config.get('Reddit', 'ClientSecret'))
        self.editable_widgets[self.clientSecretLineEdit_3] = ("Reddit", "ClientSecret")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.clientSecretLineEdit_3)
        self.usernameLabel_3 = QtWidgets.QLabel(self.reddit_tab_2)
        self.usernameLabel_3.setObjectName("usernameLabel_3")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.usernameLabel_3)
        self.usernameLineEdit_3 = QtWidgets.QLineEdit(self.reddit_tab_2)
        self.usernameLineEdit_3.setObjectName("usernameLineEdit_3")
        self.usernameLineEdit_3.setText(self.app_config.get('Reddit', 'Username'))
        self.editable_widgets[self.usernameLineEdit_3] = ("Reddit", "Username")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit_3)
        self.passwordLabel_2 = QtWidgets.QLabel(self.reddit_tab_2)
        self.passwordLabel_2.setObjectName("passwordLabel_2")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.passwordLabel_2)
        self.passwordLineEdit_2 = QtWidgets.QLineEdit(self.reddit_tab_2)
        self.passwordLineEdit_2.setObjectName("passwordLineEdit_2")
        self.editable_widgets[self.passwordLineEdit_2] = ("Reddit", "Password")
        self.hide_input(self.passwordLineEdit_2)
        self.passwordLineEdit_2.setText(self.app_config.get('Reddit', 'Password'))
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit_2)
        self.enabledLabel = QtWidgets.QLabel(self.reddit_tab_2)
        self.enabledLabel.setObjectName("enabledLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.enabledLabel)
        self.enabledCheckBox = QtWidgets.QCheckBox(self.reddit_tab_2)
        self.enabledCheckBox.setObjectName("enabledCheckBox")
        self.editable_widgets[self.enabledCheckBox] = ("Reddit", "Enabled")
        self.enabledCheckBox.setChecked(self.app_config.getboolean('Reddit', 'Enabled'))
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.enabledCheckBox)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.reddit_tab_2)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.textBrowser_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.reddit_tab_2)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.horizontalLayout_4.addLayout(self.formLayout_4)
        self.tabWidget.addTab(self.reddit_tab_2, "")
        self.buttonBox.accepted.connect(self.accepted)
        self.buttonBox.rejected.connect(self.rejected)

        # Imgur Config Layout
        self.imgur_tab_2 = QtWidgets.QWidget()
        self.imgur_tab_2.setObjectName("imgur_tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.imgur_tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.imgur_tab_2)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.textBrowser_3)
        self.clientIDLabel_4 = QtWidgets.QLabel(self.imgur_tab_2)
        self.clientIDLabel_4.setObjectName("clientIDLabel_4")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.clientIDLabel_4)
        self.clientIDLineEdit_4 = QtWidgets.QLineEdit(self.imgur_tab_2)
        self.clientIDLineEdit_4.setObjectName("clientIDLineEdit_4")
        self.editable_widgets[self.clientIDLineEdit_4] = ("Imgur", "ClientID")
        self.clientIDLineEdit_4.setText(self.app_config.get('Imgur', 'ClientID'))
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.clientIDLineEdit_4)
        self.clientSecretLabel_4 = QtWidgets.QLabel(self.imgur_tab_2)
        self.clientSecretLabel_4.setObjectName("clientSecretLabel_4")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.clientSecretLabel_4)
        self.clientSecretLineEdit_4 = QtWidgets.QLineEdit(self.imgur_tab_2)
        self.clientSecretLineEdit_4.setObjectName("clientSecretLineEdit_4")
        self.clientSecretLineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.clientSecretLineEdit_4.setText(self.app_config.get('Imgur', 'ClientSecret'))
        self.editable_widgets[self.clientSecretLineEdit_4] = ("Imgur", "ClientSecret")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.clientSecretLineEdit_4)
        self.accessTokenLabel_2 = QtWidgets.QLabel(self.imgur_tab_2)
        self.accessTokenLabel_2.setObjectName("accessTokenLabel_2")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.accessTokenLabel_2)
        self.accessTokenLineEdit_2 = QtWidgets.QLineEdit(self.imgur_tab_2)
        self.accessTokenLineEdit_2.setObjectName("accessTokenLineEdit_2")
        self.editable_widgets[self.accessTokenLineEdit_2] = ("Imgur", "AccessToken")
        self.accessTokenLineEdit_2.setText(self.app_config.get('Imgur', 'AccessToken'))
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.accessTokenLineEdit_2)
        self.refreshTokenLabel_2 = QtWidgets.QLabel(self.imgur_tab_2)
        self.refreshTokenLabel_2.setObjectName("refreshTokenLabel_2")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.refreshTokenLabel_2)
        self.refreshTokenLineEdit_2 = QtWidgets.QLineEdit(self.imgur_tab_2)
        self.refreshTokenLineEdit_2.setObjectName("refreshTokenLineEdit_2")
        self.editable_widgets[self.refreshTokenLineEdit_2] = ("Imgur", "RefreshToken")
        self.refreshTokenLineEdit_2.setText(self.app_config.get('Imgur', 'RefreshToken'))
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.refreshTokenLineEdit_2)
        self.enabledLabel_2 = QtWidgets.QLabel(self.imgur_tab_2)
        self.enabledLabel_2.setObjectName("enabledLabel_2")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.enabledLabel_2)
        self.enabledCheckBox_2 = QtWidgets.QCheckBox(self.imgur_tab_2)
        self.enabledCheckBox_2.setObjectName("enabledCheckBox_2")
        self.editable_widgets[self.enabledCheckBox_2] = ("Imgur", "Enabled")
        self.enabledCheckBox_2.setChecked(self.app_config.getboolean('Imgur', 'Enabled'))
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.enabledCheckBox_2)
        self.buttonBox_3 = QtWidgets.QDialogButtonBox(self.imgur_tab_2)
        self.buttonBox_3.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_3.setObjectName("buttonBox_3")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.buttonBox_3)
        self.horizontalLayout_2.addLayout(self.formLayout_5)
        self.tabWidget.addTab(self.imgur_tab_2, "")
        self.buttonBox_3.accepted.connect(self.accepted)
        self.buttonBox_3.rejected.connect(self.rejected)

        # Wallhaven config layout
        self.wallhaven_tab_2 = QtWidgets.QWidget()
        self.wallhaven_tab_2.setObjectName("wallhaven_tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wallhaven_tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.aPIKeyLabel_2 = QtWidgets.QLabel(self.wallhaven_tab_2)
        self.aPIKeyLabel_2.setObjectName("aPIKeyLabel_2")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.aPIKeyLabel_2)
        self.aPIKeyLineEdit_2 = QtWidgets.QLineEdit(self.wallhaven_tab_2)
        self.aPIKeyLineEdit_2.setObjectName("aPIKeyLineEdit_2")
        self.editable_widgets[self.aPIKeyLineEdit_2] = ("Wallhaven", "ApiKey")
        self.aPIKeyLineEdit_2.setText(self.app_config.get('Wallhaven', 'ApiKey'))
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.aPIKeyLineEdit_2)
        self.usernameLabel_4 = QtWidgets.QLabel(self.wallhaven_tab_2)
        self.usernameLabel_4.setObjectName("usernameLabel_4")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.usernameLabel_4)
        self.usernameLineEdit_4 = QtWidgets.QLineEdit(self.wallhaven_tab_2)
        self.editable_widgets[self.usernameLineEdit_4] = ("Wallhaven", "Username")
        self.usernameLineEdit_4.setText(self.app_config.get('Wallhaven', 'Username'))
        self.usernameLineEdit_4.setObjectName("usernameLineEdit_4")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit_4)
        self.textBrowser = QtWidgets.QTextBrowser(self.wallhaven_tab_2)
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.textBrowser)
        self.enabledLabel_3 = QtWidgets.QLabel(self.wallhaven_tab_2)
        self.enabledLabel_3.setObjectName("enabledLabel_3")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.enabledLabel_3)
        self.enabledCheckBox_3 = QtWidgets.QCheckBox(self.wallhaven_tab_2)
        self.enabledCheckBox_3.setObjectName("enabledCheckBox_3")
        self.editable_widgets[self.enabledCheckBox_3] = ("Wallhaven", "Enabled")
        self.enabledCheckBox_3.setChecked(self.app_config.getboolean('Wallhaven', 'Enabled'))
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.enabledCheckBox_3)
        self.buttonBox_4 = QtWidgets.QDialogButtonBox(self.wallhaven_tab_2)
        self.buttonBox_4.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_4.setObjectName("buttonBox_4")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buttonBox_4)
        self.horizontalLayout.addLayout(self.formLayout_6)
        self.tabWidget.addTab(self.wallhaven_tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox_4.accepted.connect(self.accepted)
        self.buttonBox_4.rejected.connect(self.rejected)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textBrowser_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.sourcesLabel.setText(_translate("Dialog", "Sources"))
        self.downloadLocationLabel.setText(_translate("Dialog", "Download Location"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.local_tab), _translate("Dialog", "Local"))
        self.clientIDLabel_3.setText(_translate("Dialog", "Client ID"))
        self.clientSecretLabel_3.setText(_translate("Dialog", "Client Secret"))
        self.usernameLabel_3.setText(_translate("Dialog", "Username"))
        self.passwordLabel_2.setText(_translate("Dialog", "Password"))
        self.enabledLabel.setText(_translate("Dialog", "Enabled"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Reddit Client Config</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reddit_tab_2), _translate("Dialog", "Reddit"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Imgur Client Config</p></body></html>"))
        self.clientIDLabel_4.setText(_translate("Dialog", "Client ID"))
        self.clientSecretLabel_4.setText(_translate("Dialog", "Client Secret"))
        self.accessTokenLabel_2.setText(_translate("Dialog", "Access Token"))
        self.refreshTokenLabel_2.setText(_translate("Dialog", "Refresh Token"))
        self.enabledLabel_2.setText(_translate("Dialog", "Enabled"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imgur_tab_2), _translate("Dialog", "Imgur"))
        self.aPIKeyLabel_2.setText(_translate("Dialog", "API Key"))
        self.usernameLabel_4.setText(_translate("Dialog", "Username"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Wallhaven Client Config</p></body></html>"))
        self.enabledLabel_3.setText(_translate("Dialog", "Enabled"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wallhaven_tab_2), _translate("Dialog", "Wallhaven"))
