

name: Build Application

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.9
    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v8
    - name: Install Dependencies
      run: |
        poetry config virtualenvs.create false --local
        poetry install
    - name: Build binary
      run: pyinstaller --onefile main.py
